### PR TITLE
modeling and endpoints creation - OT123-311

### PR DESCRIPTION
**Pull request by megastratofall**
Model creation and contact migration.
Creation of the endpoint corresponding to contact.

### CODE REVIEW

**Comment by dvelezroman** [comment]
aun no esta listo este PR... si no .. colocarle [WIP] en el titulo del mismo

**Review by dvelezroman — CHANGES_REQUESTED** [review]
Revisar... no hay nada aqui.

**Comment by dvelezroman** [comment]
Porque hubo un error

**Comment by facundoveliz** [comment]
fixed errors and moved to #35

**Pull request closed without merging**
